"""
Django settings for terraza project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
import boto3
import dj_database_url
from environs import Env
from datetime import timedelta



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = Env()
ENV_PATH = BASE_DIR.parent / ".env"
if ENV_PATH.exists():
    env.read_env(ENV_PATH)
else:
    env.read_env()


SITE_URL = env("SITE_URL")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)  # Cambiar a False en producción
ALLOWED_HOSTS = [
    "api.terrazapineda.com",
    "terrazapineda.com",
    "www.terrazapineda.com",
    ".onrender.com",
    "54.144.65.30",
    "54.172.191.58",
    "54.146.18.92",
    "127.0.0.1",
    "localhost",
    "0.0.0.0",
    "142.93.120.67",
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "https://terrazapineda.com",
    "https://www.terrazapineda.com",
    "http://localhost:5173",
    "http://localhost:3000",
    "http://192.168.100.10:5173",
    "http://192.168.100.10:3000",
    "https://54.146.18.92",
    "http://54.146.18.92",
    "https://api.terrazapineda.com",
    "http://api.terrazapineda.com",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "https://terrazapineda.com",
    "https://www.terrazapineda.com",
    "https://api.terrazapineda.com",
    "https://api.mercadopago.com",
    "https://www.mercadopago.com",
    "https://www.mercadopago.com.mx",
    "https://hooks.stripe.com",
]

# cookies pueden viajar por HTTP
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# no fuerces redirección HTTPS
SECURE_SSL_REDIRECT = False

# si tienes proxy inverso (nginx) lo puedes mantener
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    "https://terrazapineda.com",
    "https://www.terrazapineda.com",
    "https://api.terrazapineda.com",
    "http://api.terrazapineda.com",
    "http://localhost:5173",
    "http://localhost:3000",
    "http://192.168.100.10:5173",
    "http://192.168.100.10:3000",
    "http://localhost:8000",
    "http://192.168.100.10:8000",
    "http://54.146.18.92:8000",
    "https://54.146.18.92:8000",
    "https://terrazapineda-backend.onrender.com"
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
# AWS_REGION = os.environ.get('AWS_REGION')


# session = boto3.Session(
#     aws_access_key_id=AWS_ACCESS_KEY_ID,
#     aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
#     region_name=AWS_REGION
# )

# secrets_manager = session.client('secretsmanager')
# Application definition


INSTALLED_APPS = [
    #custom admin
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    #Internal apps
    'booking',
    'users',
    'store',
    'dashboard',
    'logs',

    #Exterior 
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
    'rest_framework_simplejwt.token_blacklist',
    'social_django',
    'drf_spectacular',
    'django_filters',

    
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = 'terraza.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR), 'build', os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect'
            ],
        },
    },
]


WSGI_APPLICATION = 'terraza.wsgi.application'


# Database
# https://docs.djangoproject.com/ef543fffnzz l,/4.0/ref/settings/#databases

_DATABASE_URL = os.environ.get("DATABASE_URL")
if _DATABASE_URL:
    DATABASES = {"default": dj_database_url.parse(_DATABASE_URL, conn_max_age=60, conn_health_checks=True)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'terraza',
            'USER': 'mixel',
            'PASSWORD': '3NsZ1ufzxQnu4uvkMmhZ',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")

EMAIL_USE_TLS = True

# Default from email for Django emails
DEFAULT_FROM_EMAIL = env("EMAIL_HOST_USER", default="noreply@terrazapineda.com")

# DJANGO REST FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'  # Changed to AllowAny for public endpoints
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 5,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'EXCEPTION_HANDLER': 'terraza.utils.custom_exception_handler',
}


DOMAIN =  env("DOMAIN")


SITE_URL_FRONTEND = env("FRONTEND_URL", default="https://terrazapineda.com").strip().rstrip("\\n").strip()

#DJOSER
CONTACT_EMAIL = env("CONTACT_EMAIL", default=env("EMAIL_HOST_USER", default="terrazapineda7@gmail.com"))

DJOSER = {
    'USER_ID_FIELD': 'id',
    'LOGIN_FIELD': 'email',
    'SERIALIZERS': {
        'user_create': 'users.serializers.UserCreateSerializer',
        'user': 'users.serializers.UserSerializer',
        'current_user': 'users.serializers.UserSerializer',
    },
    'EMAIL': {
        'activation': 'users.emails.CustomActivationEmail',
        'password_reset': 'users.emails.CustomPasswordResetEmail',
        'username_reset': 'users.emails.CustomUsernameResetEmail',
        'confirmation': 'users.emails.CustomConfirmationEmail',
    },
    'TOKEN_MODEL': None,
    'SEND_ACTIVATION_EMAIL': True,
    'SEND_CONFIRMATION_EMAIL': True,
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': False,
    'USERNAME_RESET_SHOW_EMAIL_NOT_FOUND': False,
    'ACTIVATION_URL': 'auth/activate/{uid}/{token}',
    'PASSWORD_RESET_CONFIRM_URL': 'auth/password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'auth/username/reset/confirm/{uid}/{token}',
}

STRIPE_PUBLIC_KEY = env("STRIPE_PUBLIC_KEY")
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_KEY = env("STRIPE_WEBHOOK_KEY")

MERCADO_PAGO_PUBLIC_KEY = env("MERCADO_PAGO_PUBLIC_KEY")
MERCADO_PAGO_ACCESS_TOKEN = env("MERCADO_PAGO_ACCESS_TOKEN")
MERCADO_PAGO_TEST_MODE = env.bool("MERCADO_PAGO_TEST_MODE", default=True)


AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env('GOOGLE_OAUTH2_CLIENT_ID', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env('GOOGLE_OAUTH2_CLIENT_SECRET', default='')
SOCIAL_AUTH_FACEBOOK_KEY = env('FACEBOOK_APP_ID', default='')
SOCIAL_AUTH_FACEBOOK_SECRET = env('FACEBOOK_APP_SECRET', default='')
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {'fields': 'id,name,email,first_name,last_name'}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=48),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# AUTH_USER_MODEL = 'booking.MyUser'
AUTH_USER_MODEL = 'users.UserAccount'



# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Google Calendar integration (Service Account)
# Set GOOGLE_SERVICE_ACCOUNT_JSON to the full JSON content of your service account key,
# or GOOGLE_SERVICE_ACCOUNT_KEY_FILE to the path of the key file.
# GOOGLE_CALENDAR_ID is the calendar to sync to — use 'primary' or a specific calendar ID.
GOOGLE_SERVICE_ACCOUNT_JSON = env("GOOGLE_SERVICE_ACCOUNT_JSON", default=None)
GOOGLE_SERVICE_ACCOUNT_KEY_FILE = env("GOOGLE_SERVICE_ACCOUNT_KEY_FILE", default=None)
GOOGLE_CALENDAR_ID = env("GOOGLE_CALENDAR_ID", default="primary")

SPECTACULAR_SETTINGS = {
    'TITLE': 'Booking API',
    'DESCRIPTION': 'API for event venue booking system',
    'VERSION': '1.0.0',
    # Add other options if needed
}
