# Generated by Django 4.2.11 on 2025-08-26 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('component', models.CharField(db_index=True, max_length=50)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', 'timestamp'], name='logs_system_level_ee87a7_idx'), models.Index(fields=['component', 'timestamp'], name='logs_system_compone_bcb251_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('email_verified', 'Email Verified'), ('account_created', 'Account Created'), ('account_deactivated', 'Account Deactivated'), ('permissions_changed', 'Permissions Changed')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='logs_userac_user_id_a33d4d_idx'), models.Index(fields=['action', 'timestamp'], name='logs_userac_action_a677f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.UUIDField(db_index=True)),
                ('order_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('initiated', 'Initiated'), ('attempted', 'Attempted'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('admin_approved', 'Admin Approved'), ('admin_rejected', 'Admin Rejected')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('method', models.CharField(blank=True, max_length=20)),
                ('gateway', models.CharField(blank=True, max_length=32)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['payment_id', 'timestamp'], name='logs_paymen_payment_dc0972_idx'), models.Index(fields=['order_id', 'timestamp'], name='logs_paymen_order_i_4638dc_idx'), models.Index(fields=['action', 'timestamp'], name='logs_paymen_action_2e43cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('payment_received', 'Payment Received'), ('reminder_sent', 'Reminder Sent'), ('review_requested', 'Review Requested')], max_length=20)),
                ('old_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['booking_id', 'timestamp'], name='logs_bookin_booking_9def79_idx'), models.Index(fields=['action', 'timestamp'], name='logs_bookin_action_80c015_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('audit_type', models.CharField(choices=[('data_change', 'Data Change'), ('permission_change', 'Permission Change'), ('configuration_change', 'Configuration Change'), ('security_event', 'Security Event'), ('compliance_check', 'Compliance Check')], max_length=20)),
                ('table_name', models.CharField(blank=True, max_length=100)),
                ('record_id', models.CharField(blank=True, max_length=100)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['audit_type', 'timestamp'], name='logs_auditl_audit_t_7347d4_idx'), models.Index(fields=['table_name', 'record_id'], name='logs_auditl_table_n_03084d_idx'), models.Index(fields=['user', 'timestamp'], name='logs_auditl_user_id_a7304b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('user', 'User'), ('admin', 'Admin'), ('system', 'System'), ('venue', 'Venue'), ('package', 'Package'), ('notification', 'Notification'), ('review', 'Review')], db_index=True, max_length=20)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('log_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'category'], name='logs_activi_timesta_9c5162_idx'), models.Index(fields=['user', 'timestamp'], name='logs_activi_user_id_0c4daf_idx'), models.Index(fields=['category', 'action'], name='logs_activi_categor_d0f806_idx'), models.Index(fields=['log_level', 'timestamp'], name='logs_activi_log_lev_c70fed_idx')],
            },
        ),
    ]
