# Generated by Django 4.2.11 on 2026-07-18 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0024_venueconfiguration_cancellation_refund_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuya_device_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('supports_color', models.BooleanField(default=False)),
                ('power_dp_code', models.CharField(default='switch_led', help_text="Tuya DP code for on/off, confirmed per device via Tuya's Device Debugging panel (e.g. switch_led, switch_1).", max_length=40)),
                ('color_dp_code', models.CharField(default='colour_data_v2', max_length=40)),
                ('color_value_scale', models.PositiveIntegerField(default=100, help_text='Max value for the s/v components of colour_data_v2 on this device (100 or 1000, varies by model).')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_devices', to='booking.venue')),
            ],
            options={
                'ordering': ['venue', 'order', 'name'],
            },
        ),
    ]
