# Generated by Django 4.2.11 on 2025-07-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='gateway',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
