# Generated by Django 4.2.11 on 2025-07-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_paymentorder_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
