# Generated by Django 4.2.11 on 2025-08-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_payment_card_last4_payment_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_photo',
            field=models.ImageField(blank=True, null=True, upload_to='payment_photos/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_photo_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
