# Generated by Django 4.2.11 on 2025-08-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_payment_payment_photo_payment_payment_photo_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('transfer', 'Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
