# Generated by Django 4.2.11 on 2026-07-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_payment_method_alter_paymentorder_amount_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión real cobrada por la pasarela de pago (Stripe/MercadoPago) sobre este pago, si aplica.', max_digits=10),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='suggested_refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='suggested_refund_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
