# Generated by Django 4.2.11 on 2025-08-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action',
            field=models.CharField(choices=[('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('booking_approved', 'Booking Approved'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('user_blocked', 'User Blocked'), ('stats_generated', 'Statistics Generated')], max_length=50),
        ),
    ]
