# Generated by Django 4.2.11 on 2025-07-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_slug_extraservice_slug_package_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(unique=True),
        ),
    ]
