# Generated by Django 4.2.11 on 2025-07-19 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0006_notification_bookingwish'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingwish',
            unique_together={('user', 'venue', 'wished_start_datetime')},
        ),
        migrations.RemoveField(
            model_name='bookingwish',
            name='package',
        ),
        migrations.RemoveField(
            model_name='bookingwish',
            name='wished_end_datetime',
        ),
    ]
