# Generated by Django 4.2.11 on 2025-08-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_description'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_eve_start_d_c3bfad_idx',
            old_name='booking_boo_start_d_64e842_idx',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='booking_event',
        ),
    ]
