# Generated by Django 4.2.11 on 2025-08-18 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_booking_boo_start_d_64e842_idx_booking_eve_start_d_c3bfad_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_boo_start_d_64e842_idx',
            old_name='booking_eve_start_d_c3bfad_idx',
        ),
        migrations.AlterModelTable(
            name='booking',
            table=None,
        ),
    ]
