# Generated by Django 4.2.11 on 2025-08-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_rename_booking_eve_start_d_c3bfad_idx_booking_boo_start_d_64e842_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_per_venue_per_day',
        ),
    ]
