# Generated by Django 4.2.11 on 2025-09-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_booking_unique_booking_per_venue_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('solicitud', 'Solicitud de Reserva'), ('aceptacion', 'Aceptación de Reserva'), ('apartado', 'Apartado inicial'), ('liquidado', 'Monto liquidado'), ('liquidado_entregado', 'Monto liquidado y lugar entregado'), ('entregado', 'Entregado'), ('finalizado', 'Reserva finalizada'), ('cancelado', 'Reserva cancelada'), ('rechazado', 'Rechazado')], default='solicitud', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
