# Generated by Django 5.2.15 on 2026-06-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_booking_status_alter_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
