# Generated by Django 6.0.6 on 2026-06-30 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_add_google_calendar_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('package', 'Package'), ('extra_service', 'Extra Service'), ('discount', 'Discount')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='booking.booking')),
            ],
        ),
    ]
