# Generated by Django 4.2.11 on 2026-07-04 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_booking_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField(default=datetime.time(10, 0))),
                ('close_time', models.TimeField(default=datetime.time(22, 0))),
            ],
            options={
                'verbose_name': 'Configuración del Venue',
                'verbose_name_plural': 'Configuración del Venue',
            },
        ),
        migrations.RemoveField(
            model_name='package',
            name='hours',
        ),
    ]
