# Generated by Django 4.2.11 on 2026-07-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_add_venueconfiguration_remove_package_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='entregado_after_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_entregado',
            field=models.BooleanField(default=False),
        ),
    ]
