# Generated by Django 4.2.11 on 2026-07-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018b_is_entregado_hora_entrega_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='entregado_after_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
