# Generated by Django 4.2.11 on 2026-07-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_coupon_discount_type_amount_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueconfiguration',
            name='minimum_deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo en pesos para el apartado inicial de una reserva.', max_digits=10, verbose_name='Apartado mínimo'),
        ),
    ]
