# Generated by Django 4.2.11 on 2026-07-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_venueconfiguration_minimum_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='minimum_deposit',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Apartado mínimo vigente al momento de crear la reserva (no cambia si la configuración cambia después).', max_digits=10),
        ),
    ]
