# Generated by Django 4.2.11 on 2026-07-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_backfill_minimum_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueconfiguration',
            name='cancellation_refund_percent',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Porcentaje del anticipo que se reembolsa al cancelar por arriba del umbral de días.', max_digits=5, verbose_name='Porcentaje de reembolso por cancelación'),
        ),
        migrations.AddField(
            model_name='venueconfiguration',
            name='cancellation_refund_threshold_days',
            field=models.PositiveIntegerField(default=45, help_text='Si se cancela con más de estos días de anticipación, aplica el porcentaje de reembolso configurado. Con menos, no hay reembolso.', verbose_name='Umbral de reembolso por cancelación (días)'),
        ),
        migrations.AddField(
            model_name='venueconfiguration',
            name='date_change_notice_days',
            field=models.PositiveIntegerField(default=21, help_text='Días mínimos de anticipación requeridos para solicitar un cambio de fecha.', verbose_name='Aviso mínimo para cambio de fecha (días)'),
        ),
    ]
